# Generated by Django 3.0.2 on 2020-01-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_color', models.CharField(max_length=255)),
                ('p_time', models.DateTimeField(auto_now_add=True)),
                ('p_image', models.ImageField(upload_to='pics')),
                ('p_content', models.TextField()),
            ],
        ),
    ]
